--- 
log_file: log/mongrel.log
port: "8000"
environment: development
pid_file: tmp/pids/mongrel.pid
servers: 5
--- 
user: www-data
cwd: /var/www/railsapp
log_file: log/mongrel.log
port: "8000"
environment: production
group: www-data
address: 127.0.0.1
pid_file: tmp/pids/mongrel.pid
servers: 3